### ISSUE TITLE
just asking for help (similar laptop) 

### ISSUE THREAD

**Issue by SuperAviation001** [taarkov/HP15-dw1002nt#1]
I have a hp 15 laptop (all the same except for no nvidia gpu) hp 15s-du1001tu and have created an efi but the hdmi doesnt work. Could you try helping with fixing up my efi so that hdmi will work? My efi is in one of my repos

**Comment by taarkov** [comment]
If the HDMI connected to the dGPU which is NVIDIA, there is no way you can use that port correctly on macOS. If not, take a look to conx-pipeline patches on FrameBuffer.

**Comment by SuperAviation001** [comment]
I have done some modifications to the laptop (removing the broken display so hdmi is forced output) and can confirm i can see what is wrong with my efi. Is the NVIDIA card on this efi's laptop disabled? Just wanna know so i can see if i can learn a thing or two from this efi.

**Comment by taarkov** [comment]
It is disabled bu -wegnoegpu. Even tho as i said before, if your display outputs use NVIDIA, you cannot use it. If you are saying that the ports arent use NVIDIA then should try framebuffers conx alldata patches.

**Comment by SuperAviation001** [comment]
Thanks man, was just asking as I have the same specs just no NVIDIA card in it.

**Comment by SuperAviation001** [comment]
closed
